# Generated by Django 6.0.6 on 2026-06-21 00:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FreqEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("word", models.CharField(db_index=True, max_length=50, unique=True)),
                ("frequency", models.IntegerField()),
            ],
            options={
                "verbose_name_plural": "freq entries",
            },
        ),
        migrations.CreateModel(
            name="ArticleToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("article_key", models.CharField(db_index=True, max_length=16)),
                ("source", models.CharField(db_index=True, max_length=200)),
                ("token", models.CharField(db_index=True, max_length=50)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["token", "article_key"],
                        name="recommender_token_637613_idx",
                    )
                ],
                "unique_together": {("article_key", "token")},
            },
        ),
        migrations.CreateModel(
            name="VocabList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vocab_lists",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
                "unique_together": {("user", "name")},
            },
        ),
        migrations.CreateModel(
            name="VocabEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("word", models.CharField(db_index=True, max_length=50)),
                (
                    "vocab_list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="recommender.vocablist",
                    ),
                ),
            ],
            options={
                "unique_together": {("vocab_list", "word")},
            },
        ),
    ]
