# Generated by Django 6.0.6 on 2026-07-25 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recommender", "0002_userprofile"),
    ]

    operations = [
        migrations.CreateModel(
            name="CharFreqEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("char", models.CharField(db_index=True, max_length=1, unique=True)),
                ("frequency", models.IntegerField()),
            ],
            options={
                "verbose_name_plural": "char freq entries",
            },
        ),
    ]
